---
- name: Create ansible facts.d dir
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: facts

- name: Create facts
  become: yes
  template:
    src: facts.fact
    dest: /etc/ansible/facts.d/custom_facts.fact
  with_subelements:
    - "{{ facts }}"
    - settings 
  tags: facts

- name: re-read facts
  setup: filter=ansible_local
  tags: facts
...
