---
- name: Create ansible facts.d dir
  file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes
  tags: facts

- name: create facts
  template:
    src: facts.fact
    dest: /etc/ansible/facts.d/{{ facts_name }}/{{ facts_sub_name }}.fact
    force: yes
  become: yes
  tags: facts
 
- name: delete rpi fact
  file:
    path: /etc/ansible/facts.d/{{ facts_name }}.fact
    state: absent
  become: yes
  tags: facts
  
- name: re-read facts
  setup: filter=ansible_local
  tags: facts
...
