---
- name: Create ansible facts.d dir
  file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes
  tags: facts

- name: Create facts
  template:
    src: facts.fact
    dest: /etc/ansible/facts.d/custom_facts.fact
    force: yes
  become: yes
  tags: facts

- name: re-read facts
  setup: filter=ansible_local
  tags: facts
...
